config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  resources :polls
  resources :profiles
  resources :votes, only: [:create]
  resources :users, only: [:show]
  root 'polls#index'

end

app/models/poll.rb
class Poll < ActiveRecord::Base
	# Sets up association between Poll and vote_options, a nested resource
	has_many :vote_options, dependent: :destroy
	# Poll must include a topic upon creation
	validates :topic, presence: true
	# Sets up attributes necessary for nested resource
	accepts_nested_attributes_for :vote_options, :reject_if => :all_blank, :allow_destroy => true

	# normalized_votes_for to be used in helper to display voting statistics on a poll
	def normalized_votes_for(option)
		votes_summary == 0 ? 0 : (option.votes.count.to_f / votes_summary) * 100
	end

	# Another method that displays voting statistics
	def votes_summary
		vote_options.inject(0) {|summary, option| summary + option.votes.count}
	end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

  # defines index method and defines instance variable @polls (an array) to be used in views/polls/index
  def index
    @polls = Poll.all
  end

  # defines new method and defines instance variable @poll to be used in views/polls/new
  def new
    @poll = Poll.new
  end

  # defines new method and defines instance variable @poll. Create will take the data inputted in the "new" form
  # and create a new poll. After a successful update, the app will redirect to the polls index (given by polls_path
  # via rake routes. Flash message is passed to javascript.)
  def create
    @poll = Poll.new(poll_params)
    if @poll.save
      flash[:success] = 'Poll was created!'
      redirect_to polls_path
    else
      render 'new'
    end
  end

  # defines edit method and defines instance variable @poll to be used in views/polls/edit
  def edit
    @poll = Poll.find_by_id(params[:id])
  end

  # defines show method and defines instance variable @poll to be used in views/polls/show
  def show
    @poll = Poll.includes(:vote_options).find_by_id(params[:id])
  end

  # defines update method and defines instance variable @poll. Update will take the data inputted in the "edit" form
  # and update an existing poll. After a successful update, the app will redirect to the polls index (given by polls_path
  # via rake routes. Flash message is passed to javascript.)
  def update
    @poll = Poll.find_by_id(params[:id])
    if @poll.update_attributes(poll_params)
      flash[:success] = 'Poll was updated!'
      redirect_to polls_path
    else
      render 'edit'
    end
  end

  # defines destroy method and defines instance variable @poll. Poll will be destroyed from database and
  # the app will redirect to the polls index (given by polls_path via rake routes.)
  # Flash message is passed to javascript.)
  def destroy
    @poll = Poll.find_by_id(params[:id])
    if @poll.destroy
      flash[:success] = "Poll was destroyed!"
    else
      flash[:warning] = "Error destroying poll"
    end
    redirect_to polls_path
  end

  private

  # defines the paramaters allowed and required to work with a poll, including the nested vote_options attributes
  def poll_params
    params.require(:poll).permit(:topic, :open, vote_options_attributes: [:id, :title, :_destroy, :correct])
  end
end

app/helpers/polls_helper.rb
module PollsHelper
# classes from bootstrap and tutorial from sitepoint, displays numbers of votes for each option in a poll
  def visualize_votes_for(option)
    content_tag :div, class: 'progress' do
      content_tag :div, class: 'progress-bar',
                  style: "width: #{option.poll.normalized_votes_for(option)}%" do
        "#{option.votes.count}"
      end
    end
  end
end

app/views/polls/_form.html.erb
<!-- Form partial to be rendered in other views when necessary -->
<%= form_for @poll do |f| %>
  <!-- Renders error form -->
  <%= render 'shared/errors', object: @poll %>

  <!-- Bootstrap and form_for syntax to set up label and input for topic of poll -->
  <div class="form-group">
    <%= f.label :topic %>
    <%= f.text_area :topic, rows: 3, required: true, class: 'form-control' %>

  </div>

  <!-- Bootstrap to set up vote_options of poll. vote_option_fields partial is rendered for each option, so that
  options do not need to be hard-coded into the form; the partial can just be called whenever a new association 
  (vote_option) is added. This can be done by the link_to_add_association at the bottom. -->
  <div class="panel panel-default">
    <div class="panel-heading">Options</div>
    <div class="panel-body">
      <%= f.fields_for :vote_options do |options_form| %>
        <%= render 'vote_option_fields', f: options_form %>
      <% end %>

      <div class="links">
        <%= link_to_add_association 'add option', f, :vote_options %>
      </div>
    </div>
  </div>

  	<!-- Checkbox to toggle "open" boolean -->
	<%= f.label "Open?" %> <br />
    <%= f.check_box :open %> <br />

  <br>

  <!-- Submission button, labeled create -->
  <%= f.submit 'Create', class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/polls/_vote_option.html.erb
<!-- Ensures that user has not voted for and that the poll is still open before a user can vote, then shows radio
buttons next to each vote_option. Statistics for the event will only be shown after user has cast vote. -->
<div class="form-group">
  <%= content_tag(:label) do %>
    <% unless current_user.voted_for?(@poll) || !@poll.open? %>
      <%= radio_button_tag 'vote_option[id]', option.id %>
    <% end %>
    <%= option.title %>
  <% end %>
  <%= visualize_votes_for option %>
</div>

app/views/polls/_vote_option_fields.html.erb
<!-- Creates "block" to create a vote_option as a partial that can be called as many times as needed to create as many options as needed. -->
<div class="nested-fields">
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', required: true %>
  </div>

  <%= f.label "Correct?" %> <br />
  <%= f.check_box :correct %> <br />
  <%= link_to_remove_association "remove option", f %>
  
</div>
<br>
<br>

app/views/polls/_voting_form.html.erb
<!-- Creates basic form for users to cast vote, which renders the vote_option partial in this same folder. -->
<%= form_tag votes_path, method: :post, remote: true, id: 'voting_form' do %>
	<%= hidden_field_tag 'poll[id]', @poll.id %>

	<%= render partial: 'polls/vote_option', collection: @poll.vote_options, as: :option %>

	<!-- Ensures that user can only cast vote if they have not voted on this poll yet and the poll is still open. Page informs user of errors if user is unable to vote. -->
	<% if current_user.voted_for?(@poll) %>
		<p>You have already voted!</p>
	<% else %>
		<% if @poll.open? %>
			<%= submit_tag 'Vote', class: 'btn btn-lg btn-primary' %>
		<% else %>
			<p> This poll is now closed </p>
		<% end %>
	<% end %>
<% end %>

app/views/polls/edit.html.erb
<!-- Edit form for polls, renders form -->
<% content_for(:page_header) {"Edit poll"} %>

<%= render 'form' %>

app/views/polls/index.html.erb
<!-- Top header of page -->
<% content_for(:page_header) {"Predict now!"} %>

<!-- Shows all polls only if user signed in. For each poll, topic is displayed as well as the number of users who have already voted. -->
<% if user_signed_in? %>
	<% @polls.each do |poll| %>
		
		<div class = "well">
			<h2><%= poll.topic %> <small>(voted: <%= poll.votes_summary %>)</small></h2>

			<!-- Unless you are a user, you can only see a link to participate in a poll if it is open. -->
			<% if poll.open? || current_user.admin? %>
				<p>
					<% if current_user %>
						<%= link_to 'Participate!', poll_path(poll), class: 'btn btn-primary btn-lg block' %>			
					<% end %>
				</p>

				<!-- You can only Edit and Delete polls if you are an admin. -->
				<% if current_user.admin? %>
					<div class = "btn-group">
						<%= link_to "Edit", edit_poll_path(poll), class: "btn btn-default" %>
						<%= link_to "Delete", poll_path(poll), method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure?"} %>
					</div>
				<% end %>

			<!-- If you are not an admin and the poll is closed, you may only view results -->
			<% else %>
				<p>This event is now closed </p>
				<%= link_to 'View Results', poll_path(poll), class: 'btn btn-primary btn-lg block' %>
			<% end %>
		</div>

	<% end %>

<!-- If you are not logged in, we encourage you to do so. -->
<% else %>
	Please <%= link_to 'sign in', new_user_session_path %> or <%= link_to "sign up", new_user_registration_path %> to view events.
<% end %>

app/views/polls/new.html.erb
<!-- Form to create a new poll, from rendered partial (same as is used in edit) -->
<% content_for(:page_header) {"Create a new poll"} %>

<%= render 'form' %>

app/views/polls/show.html.erb
<% content_for(:page_header) {"Share your opinion"} %>

<!-- Shows poll topic and renders partial form for voting -->
<h2><%= @poll.topic %></h2>

<%= render 'voting_form' %>

<%= link_to 'Back', root_path %>