config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  resources :polls
  resources :profiles
  resources :votes, only: [:create]
  resources :users, only: [:show]
  root 'polls#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EAPoll</title>
<!-- Links in stylesheets and javascript to use in navbar -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<!-- Sets up dynamic navbar with bootstrap -->
  	<div class="navbar navbar-inverse">
  		<div class="container">
    		<div class="navbar-header">
      			<%= link_to 'Effective Altruism Game', root_path, class: 'navbar-brand' %>
    		</div>
    		<ul class="nav navbar-nav">
    			<!-- Allows only admins to see add event link -->
    			<% if current_user.try(:admin?) %>
	      			<li><%= link_to 'Add event', new_poll_path %></li>
	      		<% end %>

	      		<!-- Allows only authenticated, signed-in users to view profiles and edit/create their own. -->
				<% if user_signed_in? %>
				<li>
					<% if user_signed_in? %>
						<% if current_user.profile %>
							<% if current_page? profile_path(current_user.profile) %>
								<%= link_to "Edit My Profile", edit_profile_path(current_user.profile) %>
							<% else %>
								<%= link_to "View My Profile", profile_path(current_user.profile) %>
							<% end %>
						<% else %>
							<%= link_to "Create Profile", new_profile_path %>
						<% end %>
					<% end %>
				</li>
		<% end %>

		<!-- Links to profile index  -->
		<li><%= link_to "See who's playing!", profiles_path, :class => 'navbar-link' %></li>

		<!-- Only signed in, authenticated users can edit their user info. If a user is logged in, the logout link
		will also be displayed. -->
		<% if user_signed_in? %>
			<li><%= link_to 'Edit user', edit_user_registration_path, :class => 'navbar-link' %></li>
			<li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
		<!-- If user is not logged in, one can sign up or log in -->
		<% else %>
			<li><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %></li>
			<li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
		<% end %>

	    	</ul>
  		</div>
	</div>

	<!-- Bootstrap flash message formatting -->
	<div class="container">
  		<% flash.each do |key, value| %>
	    <div class="alert alert-<%= key %>">
	      <%= value %>
	    </div>
	<% end %>

  	<div class="page-header">
    	<h1><%= yield :page_header %></h1>
  	</div>

  	<%= yield %>
</div>
</head>
<body>


</body>
</html>